import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const desktopRoot = path.resolve(__dirname, "..");
const outFile = path.join(desktopRoot, "src/shared/baked-crm-url.ts");
const urlFile = path.join(desktopRoot, "crm-app.url");

function stripUrl(value) {
  return value.trim().replace(/\/$/, "");
}

function readUrlFile(filePath) {
  if (!fs.existsSync(filePath)) return null;
  const line = fs
    .readFileSync(filePath, "utf8")
    .split(/\r?\n/)
    .map((row) => row.trim())
    .find((row) => row && !row.startsWith("#"));
  if (!line) return null;
  return stripUrl(line);
}

function readEnvValue(filePath, key) {
  if (!fs.existsSync(filePath)) return null;
  const prefix = `${key}=`;
  const match = fs
    .readFileSync(filePath, "utf8")
    .split(/\r?\n/)
    .map((row) => row.trim())
    .find((row) => row.startsWith(prefix));
  if (!match) return null;
  const value = match.slice(prefix.length).trim().replace(/^["']|["']$/g, "");
  return value ? stripUrl(value) : null;
}

function readAppUrlFromWebEnv() {
  return readEnvValue(path.join(desktopRoot, "../web/.env"), "APP_URL");
}

function readCrmUrlFromRootEnv() {
  return readEnvValue(path.join(desktopRoot, "../..", ".env"), "CRM_APP_URL");
}

function isLocalhost(url) {
  try {
    const host = new URL(url).hostname;
    return host === "localhost" || host === "127.0.0.1";
  } catch {
    return false;
  }
}

const requireProduction = process.argv.includes("--production");
const fromEnv = process.env.CRM_APP_URL?.trim();
const fromFile = readUrlFile(urlFile);
const fromRootEnv = readCrmUrlFromRootEnv();
const fromWebEnv = readAppUrlFromWebEnv();
const resolved = stripUrl(fromEnv || fromFile || fromRootEnv || fromWebEnv || "__LOCALHOST__");

if (requireProduction && (resolved === "__LOCALHOST__" || isLocalhost(resolved))) {
  console.error(
    [
      "Desktop build needs a live CRM URL.",
      "",
      "Create apps/desktop/crm-app.url with one line, for example:",
      "  https://your-live-crm.example.com",
      "",
      "Or run:",
      "  CRM_APP_URL=https://your-live-crm.example.com npm run build:desktop"
    ].join("\n")
  );
  process.exit(1);
}

const baked = resolved === "__LOCALHOST__" || isLocalhost(resolved) ? "__LOCALHOST__" : resolved;

fs.writeFileSync(
  outFile,
  `/** Generated by scripts/bake-crm-url.mjs — do not edit by hand. */\nexport const BAKED_CRM_APP_URL: string = ${JSON.stringify(baked)};\n`,
  "utf8"
);

console.log(`Baked CRM URL: ${baked === "__LOCALHOST__" ? "http://localhost:3000 (dev)" : baked}`);
